version: '3'
services:
  api:
    container_name: fishare-api
    build: ./backend/
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/api
    ports:
      - 3001:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    container_name: fishare-db
    image: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  front:
    container_name: fishare-front
    build: ./frontend/
    command: /bin/sh -c "npm start"
    volumes:
      - ./frontend/app:/front
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
      - db
  mailcatcher:
    container_name: fishare-mailcatcher
    image: schickling/mailcatcher
    ports:
      - 1080:1080 # Webインターフェース用
      - 1025:1025 # SMTP用
volumes:
  db-volume: {}
