source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "rails", "~> 7.0.8"
gem 'pg', '~> 1.3'
gem "puma", "~> 5.0"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false
gem "rack-cors"
gem 'pry-rails'
gem 'active_model_serializers'
gem 'audited'
gem 'sidekiq'
gem 'redis', '~> 4.0'
gem 'devise'
gem 'devise_token_auth'

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem 'rspec-rails', '~> 7.0'
  gem 'factory_bot_rails', '~> 6.0'
  gem 'faker'
end

group :development do
  gem 'rubocop', require: false
  gem 'annotate'
end

group :test do
  gem 'test-prof', '~> 1.0'
end
