version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.1
    working_directory: ~/fishare/backend
    steps:
      - checkout:
          path: ~/fishare
      - run:
          name: Ensure backend directory exists
          command: ls ~/fishare/backend
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "backend/Gemfile.lock" }}
            - v1-deps-
      - run:
          name: Install Ruby dependencies
          command: |
            cd backend
            bundle install
      - save_cache:
          paths:
            - backend/vendor/bundle
          key: v1-deps-{{ checksum "backend/Gemfile.lock" }}
  test:
    docker:
      - image: cimg/ruby:3.1.1
      - image: circleci/postgres
        environment:
          POSTGRES_HOST: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      POSTGRES_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/fishare/backend
    steps:
      - checkout:
          path: ~/fishare
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "backend/Gemfile.lock" }}
      - run:
          name: Install Ruby dependencies
          command: |
            cd backend
            bundle install
      - run:
          name: Create Database
          command: bundle exec rails db:create RAILS_ENV=test
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: Test
          command: bundle exec rspec spec

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
