default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD")  { 'password' } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { 'db' } %>

development:
  <<: *default
  database: develop_db

test:
  <<: *default
  database: test_db

production:
  <<: *default
  database: <%= Aws::SSM::Client.new.get_parameter(name: "/fishare/production/POSTGRES_DB", with_decryption: true).parameter.value rescue nil %>
  host: <%= Aws::SSM::Client.new.get_parameter(name: "/fishare/production/POSTGRES_HOST", with_decryption: true).parameter.value rescue nil %>
  username: <%= Aws::SSM::Client.new.get_parameter(name: "/fishare/production/POSTGRES_USER", with_decryption: true).parameter.value rescue nil %>
  password: <%= Aws::SSM::Client.new.get_parameter(name: "/fishare/production/POSTGRES_PASSWORD", with_decryption: true).parameter.value rescue nil %>
